#!/usr/bin/perl
# Apache profiler PoC script
# Written by Eldar "WIreghoul" Marcussen - http://www.justanotherhacker.com

use strict;
use warnings;
use IO::Socket::INET;
use IO::Socket::SSL;
use Getopt::Long;

my $VERSION = '0.1';
my $AUTHOR = 'Eldar "Wireghoul" Marcussen';
my ($ssl, $target, $timeout, $sock, $force);
my $port = 80;

my $opts = GetOptions(
        "ssl" => \$ssl,
        "port=i" => \$port,
        "timeout" => \$timeout,
	"force" => \$force,
        "version" => sub { print "aprof version: $VERSION\n"; exit 0; }
);

&show_help unless $ARGV[0];
$target = $ARGV[0];
&banner;

# General stuff here
print "Analysing: $target\n";
if (!$force) {
    my $tmp = &check_is_apache;
    if (!$tmp) {
        print "Server does not appear to be apache (run with --force if you think the server is faking it)\n";
        exit;
    }
    print "Server signature: Apache$tmp\n";
}

# Module detection here
print "Attempting to identify modules:\n";
&check_default_host;
&check_mod_alias;
&check_mod_caucho;
&check_mod_cgi;
&check_mod_dav;
&check_mod_deflate;
&check_mod_imagemap;
&check_mod_info;
&check_mod_php;
&check_mod_status;
&check_mod_setenvif;
&check_Frontpage;

print "Done!\n\n";

sub check_is_apache {
    if ( &request("GET / HTTP/1.1\r\nHost: $target") =~ m{^Server: Apache(.*)$}m ) {
        return $1;
    }
}

sub check_default_host {
    return;
}

sub check_mod_alias {
    return;
}

sub check_mod_php {
    my $php = 0;
    if ( &request("GET / HTTP/1.1\r\nHost: $target") =~ m{^(X-Powered-By: PHP|Set-Cookie: PHPSESSID|Server: .* PHP/)}m ) {
        print "mod_php detected\n";
        $php = 1;
    } elsif ( &request("GETSPHP /index.php HTTP/1.1\r\nHost: $target") =~ m{^HTTP/1.. (200|30[12]|404|500)} && &request("GETSPHP /notaphp.file HTTP/1.1\r\nHost: $target") =~ m{^HTTP/1.. 501} ) {
        print "mod_php detected\n";
        $php = 1;
    }
    if ($php) {
        print "Checking what extensions have php bindings:\n";
        foreach my $ext ('.php','.php3','.php4','.php5','.phtml','.phps') {
            print "$ext ... ";
            if (&request("GETSPHP /index$ext HTTP/1.1\r\nHost: $target") =~ m{^HTTP/1.. (200|30[12]|404|500)}) {
                print "in use\n"
            } else {
                print "not in use\n";
            }
        }
    }
}

sub check_mod_caucho {
    if ( &request("GET /caucho-status HTTP/1.0") =~ m{(Server: .* Resin/|Status : Caucho Servlet Engine)}m) {
        print "mod_caucho detected\n";
    }
}

sub check_mod_cgi {
    if ( &request("GETCGI /cgi-bin/ HTTP/1.1\r\nHost: $target") =~ m{^HTTP/1.. (200|30[12]|403|500)} && &request("GETCGI /notacgi.gob HTTP/1.1\r\nHost: $target") =~ m{^HTTP/1.. 501} ) {
        print "mod_cgi detected\n";
    }
}

sub check_mod_dav {
    return;
}

sub check_mod_deflate {
    return;
}

sub check_mod_imagemap {
    if ( &request("GETSMAP /image.map HTTP/1.0") =~ m{^HTTP/1.. (200|404|500)} ) {
        print "mod_imagemap detected\n";
    }
}

sub check_mod_info {
    my $response = &request("GET /server-info HTTP/1.1\r\nHost: $target");
    if ( $response =~ m{^HTTP/1.. 403} ) {
        print "mod_info (restricted access) detected\n";
    } elsif ( $response =~ m{Apache Server Information} ) {
        print "mod_info (public access) detected - http://$target:$port/server-info\n"; # Should be parsed for 100% accurate information
    }
}

sub check_mod_ldap {
    my $response = &request("GET /ldap-status HTTP/1.1\r\nHost: $target");
    if ( $response =~ m{^HTTP/1.. 403} ) {
        print "mod_ldap (restricted access) detected\n";
    } elsif ( $response =~ m{Apache ldap} ) {
        print "mod_ldap (public access) detected\n";
    }
}

sub check_mod_qos {
    if ( &request("GET /qos HTTP/1.0") =~ m{^HTTP/1.. (200|403)} ) {
        print "mod_qos detected\n";
    }
}

sub check_mod_status {
    my $response = &request("GET /server-status/ HTTP/1.1\r\nHost: $target");
    if ( $response =~ m{^HTTP/1.. 403} ) { 
        print "mod_status (restricted access) detected\n";
    } elsif ( $response =~ m{Apache Status} ) {
        print "mod_status (public access";
        if ($response !~ m{ExtendedStatus On}) {
     	    print " - full status";
        } else {
            print " - limited status";
        }
	print ") detected http://$target:$port/server-status/\n";
    }
}

sub check_mod_setenvif {
    return;
}

sub check_Frontpage {
    if ( &request("GET /_vti_bin/ HTTP/1.1\r\nHost: $target") =~ m{^HTTP/1.. 200} ) {
        print "Frontpage detected\n";
    }
}

sub request {
# Need timeout
    my $request = shift;
    my $resp = '';
    if (&connect($target, $port, $timeout)) {
        print $sock "$request\r\nConnection: Close\r\n\r\n";
        while (<$sock>) {
            $resp .= $_;
        }
    }
#    warn "DEBUG:\n".$resp;
    return $resp;
}

sub connect {
    my ($target, $port, $timout) = @_;
    if ($ssl) {
	$sock = IO::Socket::SSL->new("$target:$port") or die "Unable to connect to $target: $!\n";
    } else {
        $sock = IO::Socket::INET->new("$target:$port") or die "Unable to connect to $target: $!\n";
    }
    # Reconnect attempts?
    return 1 if ($sock);
}
       
sub show_help {
    &banner;
    print "Usage: $0 <hostname>\n";
    exit;
}

sub banner {
    print "aprof - Apache profiler script v $VERSION\n";
    print "Written by $AUTHOR - http://www.justanotherhacker.com\n";
}
