#!/bin/bash

rm -f tmp/*.log
while read LINE ; do
	./htfuzz.pl $LINE > tmp/$LINE.log &
	echo "$LINE"
	read LINE        
        if [ ! -z "$LINE" ]; then
                echo "$LINE"
                ./htfuzz.pl $LINE > tmp/$LINE.log &
        fi
	read LINE
	if [ ! -z "$LINE" ]; then
		echo "$LINE"
		./htfuzz.pl $LINE > tmp/$LINE.log &
	fi
        read LINE
        if [ ! -z "$LINE" ]; then
                echo "$LINE"
                ./htfuzz.pl $LINE > tmp/$LINE.log &
        fi
        read LINE
        if [ ! -z "$LINE" ]; then
                echo "$LINE"
                ./htfuzz.pl $LINE > tmp/$LINE.log
        fi
done < $1
echo "...."
wait
beep
echo '[*] Fuzzing complete'
