#!/usr/bin/perl

use strict;
use warnings;
use lib './lib';
use lbmap::Signature;
use Getopt::Long;
use IO::Socket::INET;
use IO::Socket::SSL;
use Data::Dumper;

my $VERSION = '0.1';
my $AUTHOR = 'Eldar "Wireghoul" Marcussen';
my ($sock, $ssl, $verbose, $host, $port, $fp_data);

$port = 80;
my $opts = GetOptions(
	"ssl" => \$ssl,
	"port=i" => \$port,
	"verbose" => \$verbose,
);

&help unless $ARGV[0];
$host = $ARGV[0];

sub help {
	print "Usage: $0 <options> host\n";
	exit;
}

#print Dumper($fp_data);
&lbmap;

sub lbmap {
	my %rq = %{ $fp_data->{'request'} };
	foreach my $key (keys( %rq )) {
		print "[i] $rq{$key}\n" if $verbose;
		my $resp = &request($rq{$key});
		&validate($resp,$key);
	}
}

sub get_baseline { #Not needed?
	# Base response for http/0.9 request
	# Base response for default page
	# Base response for 404 page
}

sub request {
	my $request = shift;
	my $response = '';
	&connect;
	if ($sock) {
		print $sock $request;
		while (<$sock>) {
			$response .= $_;
		}
		close ($sock);
	}
	return $response;
}

sub validate {
	my $response = shift;
	my $key = shift;
	my %validator = %{ $fp_data->{'response'} };
	if ($response =~ /$validator{$key}/) {
		print "[=] $key\n";
	}
}

sub connect {
	if ($ssl) {
		$sock = IO::Socket::SSL->new(
	                PeerAddr => "$host",
        	        PeerPort => "$port",
		) or die "Unable to connect: $!\n";
	} else {
		$sock = IO::Socket::INET->new(
	                PeerAddr => "$host",
        	        PeerPort => "$port",
		) or die "Unable to connect: $!\n";
	}
}

sub BEGIN {
	# Fingerprinting data goes here!
	$fp_data = {
		'request' => { 
			'perlbal' => "GET   /   HTTP/1.0\r\nConnection: Close\r\n\r\n",
			'haproxy' => "OPTIONS # VERB\r\nConnection: Close\r\n\r\n", # Need better haproxy detection
			'pound' => "NINJAS NINJAS NINJAS\r\nConnection: Close\r\n\r\n",
		},
		'response' => { 
			'perlbal' => 'HTTP/... 502', 
			'haproxy' => 'HTTP/... 400',
			'pound' => 'HTTP/... 501',
		},
	};
}
